Use mutex when TM is not available
sphde/sphde pull request #47
Opened 2018-05-02 14:43 UTC by rzinsly

Currently if HTM is not available multi-producer multi-consumer
queues don't work, this patch uses mutex as a fallback when HTM is
disabled by the user or TM is disabled by the kernel.

Note that the API has changed for affected functions.
Function names changed s/HTM/Sync/:

    SPHMPMCQAllocStrideDirectSync
    SPHMPMCQGetNextCompleteDirectSync

2018-05-02 17:07 UTC, munroesj52 commented
I dont think you can use a mutex here. SPHDE storage is shared and persistent. Mutexes are may or may not be shared and are not persistent.

I can't tell if StdC++ Mutex is shared (multi-process scope) or not. And again is likely not persistent-able (will leave dangling pointers to process local storage.) This is an invitation for deadlock after a crash situations and very difficult to recover from. 

That is why SPHDE has it own lock mechanism <https://sphde.github.io/saslock_8h.html> which is address hash based (the SPHDE object address is the unique lock key) and is maintained in separate, shared memory, that is not file persisted. This simplifies recovery.

SASLock (queue, SasUserLock__WRITE);
  ...
SASUnlock (queue);

2018-05-09 19:58 UTC, rzinsly commented
I changed the code to use SASLock but the sphmultipcqueue_t test is stalling when I use an old version of GCC (< 6). Any hints on why?
For the record the record my old patch is available here https://github.com/rzinsly/sphde/tree/handle_tm_mutex.

2018-05-09 21:16 UTC, munroesj52 commented
Will need a little more context, compiler versions that failed, platform and target used etc.

That there might be a compiler bug that effects the saslock is not surprising. but need to narrow it down a bit. 

Also would need the source you actually tested. I don't see that in the branch ....

2021-12-03 12:49 UTC, tuliom commented
I wonder if we can ignore GCC < 6 for now.
@rzinsly Could you rebase your PR, please?

2021-12-15 22:47 UTC, tuliom requested changes

2021-12-17 18:42 UTC, tuliom approved these changes
I missed a src/Makefile.in, but I think we can fix this shortly.
LGTM.

2021-12-17 18:44 UTC, merged