Fix failures on sphgtod_t and sphgettime_t, Issue #56
sphde/sphde pull request #65
Opened 2021-12-02 20:46 UTC by munroesj52

This can only happen on PPC as sphde was trying meet hard-realtime
requirement by using the hardware timebase directly and avoiding the
gettimeofday() and clock_gettime() syscalls.

This can experience "lost-time" in highly virtualized environments
where the virtual machine will stop the user-level timebase, while
switched to another VM. but the clock on the wall continues.

So change the error return code when ALLOWABLE_DRIFT is exceeded
to be 77 (skip test).
 
 	* src/tests/sphgettime_t.c (main):
 	Change error return code to 77.
 	* src/tests/sphgtod_t.c (main):
 	Change error return codes to 77.

2021-12-03 19:39 UTC, rzinsly requested changes

2021-12-03 19:39 UTC, rzinsly commented on src/tests/sphgettime_t.c
> +     return 77; /* SKIP */
The line 81 should be changed as well.

2021-12-03 21:49 UTC, munroesj52 commented on src/tests/sphgettime_t.c
> +     return 77; /* SKIP */
OK, update comitted.

2021-12-06 14:23 UTC, rzinsly approved these changes
LGTM
I squashed the two commits and pushed as 37cada3 to avoid the other unnecessary commits.
Thanks!

2021-12-06 14:23 UTC, closed without merging